include tests/vsdg/traverser/Makefile.sub

TESTS+=\
	vsdg/test-cse \
	vsdg/test-gamma \
	vsdg/test-graph \
	vsdg/test-nodes \
	vsdg/test-phi \
	vsdg/test-statemux \
	vsdg/test-theta \
	vsdg/test-typemismatch \
