include tests/vsdg/traverser/Makefile.sub

TESTS+=\
	vsdg/test-empty_graph_pruning \
	vsdg/test-gamma \
	vsdg/test-graph \
	vsdg/test-phi \
	vsdg/test-prune-replace \
	vsdg/test-rescls-count \
	vsdg/test-statesplit \
	vsdg/test-typemismatch \
