include tests/vsdg/traverser/Makefile.sub

TESTS+=\
	vsdg/test-cse \
	vsdg/test-gamma \
	vsdg/test-graph \
	vsdg/test-phi \
	vsdg/test-rescls-count \
	vsdg/test-statesplit \
	vsdg/test-typemismatch \
