TESTS+=\
	i386/abstract-match\
	i386/hello-world\
	i386/hello-world-gencall\
	i386/named-function-def\
	i386/simple-function\
	i386/simple-match\
	i386/simple-regalloc\
	i386/test-instr-match\
	i386/test-loadstore-match\
	i386/test-resolve-reloc\
	i386/test-simple-branch\
	i386/test-subroutine-convert\

	#i386/arithmetic-function\
	#i386/dotproduct\
	#i386/match\
