TESTS += \
	util/test-bitstring \
	util/test-double \
	util/test-float \
	util/test-hash \
	util/test-math \
	util/test-metacontainers \
	util/test-rangemap \
	util/test-set \
	util/test-sort \
	util/test-stack \
