include tests/types/bitstring/Makefile.sub
include tests/types/float/Makefile.sub
include tests/types/function/Makefile.sub
include tests/types/record/Makefile.sub
include tests/types/union/Makefile.sub
