TESTS += \
	serialization/test-bitstring-serialization \
	serialization/test-grammar \
	serialization/test-i386-serialization \
	serialization/test-label-serialization \
	serialization/test-region-serialization \
	serialization/test-rescls-serialization \
