TESTS= \
	test-context \

include tests/arch/Makefile.sub
include tests/function/Makefile.sub
include tests/i386/Makefile.sub
include tests/record/Makefile.sub
include tests/regalloc/Makefile.sub
include tests/shape/Makefile.sub
include tests/serialization/Makefile.sub
include tests/transforms/Makefile.sub
include tests/types/Makefile.sub
include tests/union/Makefile.sub
include tests/util/Makefile.sub
include tests/vsdg/Makefile.sub

TESTPROGS=$(patsubst %, tests/%, $(TESTS))

SOURCES += $(patsubst %, %.c, $(TESTPROGS)) tests/testarch.c

$(TESTPROGS): LDFLAGS+=-L. -Wl,-whole-archive -ljive -Wl,-no-whole-archive
$(TESTPROGS): %: %.la tests/testarch.la libjive.a
	$(CC) -o $@ $(filter %.la, $^) $(LDFLAGS)

$(patsubst %, tests/%.la, $(TESTS)): CPPFLAGS+=-Itests
$(patsubst %, .dep/tests/%.la.d, $(TESTS)): CPPFLAGS+=-Itests
$(patsubst %, .dep/tests/%.lo.d, $(TESTS)): CPPFLAGS+=-Itests

TESTLOG=true

check: $(TESTPROGS)
	rm -rf check.log
	@FAILED_TESTS="" ; \
	for TEST in $(TESTPROGS); do \
		$(TESTLOG) -n "$$TEST: " ; if $$TEST >>check.log 2>&1 ; then $(TESTLOG) pass ; else $(TESTLOG) FAIL ; FAILED_TESTS="$$FAILED_TESTS $$TEST" ; fi ; \
	done ; \
	if [ "x$$FAILED_TESTS" != x ] ; then echo "Failed tests:$$FAILED_TESTS" ; else echo "All tests passed" ; fi

valgrind-check: $(TESTPROGS)
	rm -rf check.log
	@FAILED_TESTS="" ; \
	for TEST in $(TESTPROGS); do \
		$(TESTLOG) -n "$$TEST: " ; if valgrind --error-exitcode=1 $$TEST >>check.log 2>&1 ; then $(TESTLOG) pass ; else $(TESTLOG) FAIL ; FAILED_TESTS="$$FAILED_TESTS $$TEST" ; fi ; \
	done ; \
	if [ "x$$FAILED_TESTS" != x ] ; then echo "Failed tests:$$FAILED_TESTS" ; else echo "All tests passed" ; fi
