TESTS += \
	arch/address-transform/test-address-transform \
	arch/address-transform/test-address-transform-nodes \
	arch/address-transform/test-apply_transform \
	arch/address-transform/test-containerof-transform \
	arch/address-transform/test-memberof-transform \
