TESTS += \
	shape/test-crossing-arc \
	shape/test-gate \
	shape/test-interference \
	shape/test-iteration \
	shape/test-loop \
	shape/test-loop-subregion \
	shape/test-reroute-gamma1 \
	shape/test-reroute-gamma2 \
	shape/test-reroute-gamma3 \
	shape/test-reroute-theta1 \
	shape/test-reroute-theta2 \
	shape/test-rescls-shape \
	shape/test-selector \
	shape/test-simple \
