LIBJIVE_I386_SRC = \
	instructionset.c \
	registerset.c \
	classifier.c \
	instrmatch.c \
	subroutine.c \
	machine.c \
	call.c \
	relocation.c \

LIBJIVE_SRC += \
	$(patsubst %, src/backend/i386/%, $(LIBJIVE_I386_SRC))
