LIBJIVE_I386_SRC = \
	call.cpp \
	classifier.cpp \
	instructionmatch.cpp \
	instructionset.cpp \
	registerset.cpp \
	relocation.cpp \
	subroutine.cpp \

LIBJIVE_SRC += \
	$(patsubst %, src/backend/i386/%, $(LIBJIVE_I386_SRC))
