TESTS+=\
	regalloc/test-gatesplit \
	regalloc/test-gateevict \
	regalloc/test-loop-overflow \
	regalloc/test-regmismatch \
	regalloc/test-shape-split \
	regalloc/test-simple \
	regalloc/test-split \
	regalloc/test-twoop \
