TESTS+=\
	regalloc/shaping-traverser \
	regalloc/simple-shaping \

#TESTS+=\
#	regalloc/test_rat
#
#tests/regalloc/test_rat: tests/regalloc/rat.o

tests/regalloc/simple-shaping: tests/regalloc/testarch.o
