TESTS+=\
	arch/test-dynamic-stackslots \
	arch/test-loadstore \
	arch/test-subroutine \
	arch/test-address \
	arch/test-dataobj \
	arch/test-memory-type \
	arch/test-sizeof \
	arch/test_label_nodes \
	arch/test-address-transform-nodes \
	arch/test-call \
	arch/test-address-transform \
	arch/test-memberof-transform \
