TESTS+=\
	arch/test-address \
	arch/test-call \
	arch/test-dynamic-stackslots \
	arch/test-label-nodes \
	arch/test-load \
	arch/test-memory-type \
	arch/test-regselect \
	arch/test-relocation \
	arch/test-sizeof \
	arch/test-store \
	arch/test-subroutine \

include tests/arch/address-transform/Makefile.sub
