TESTS+=\
	types/bitstring/comparison/test-bitequal \
	types/bitstring/comparison/test-bitnotequal \
	types/bitstring/comparison/test-bitsless \
	types/bitstring/comparison/test-bituless \
	types/bitstring/comparison/test-bitslesseq \
	types/bitstring/comparison/test-bitulesseq \
	types/bitstring/comparison/test-bitsgreater \
	types/bitstring/comparison/test-bitugreater \
	types/bitstring/comparison/test-bitsgreatereq \
	types/bitstring/comparison/test-bitugreatereq \
