TESTS+=\
	types/bitstring/slice-concat \
	types/bitstring/reduction \
	types/bitstring/test-bitstring-operations \
	types/bitstring/test-constant \
	types/bitstring/test-arithmetic \
	types/bitstring/test-normalize \

include tests/types/bitstring/arithmetic/Makefile.sub
include tests/types/bitstring/comparison/Makefile.sub
