TESTS+=\
	types/bitstring/test-arithmetic \
	types/bitstring/test-constant \
	types/bitstring/test-normalize \
	types/bitstring/test-reduction \
	types/bitstring/test-slice-concat \
	types/bitstring/test-value-representation \

include tests/types/bitstring/arithmetic/Makefile.sub
include tests/types/bitstring/comparison/Makefile.sub
